name: "Post-Run Action"
description: "A simple GitHub action that enables running post-run tasks, once a workflow job has ended."

inputs:
  run:
    description: "A command that needs to be run."
    required: true
    default: echo "This is a post-action command..."

  working-directory:
    description: "A working directory from which the command needs to be run."
    required: false
    
  skip-on-failure:
    description: "Set to true to not run the command if the job fails."
    required: false
    default: false

runs:
  using: node12
  main: dist/main/index.js
  post: dist/post/index.js
  post-if: ${{ env.INPUT_SKIP-ON-FAILURE != 'true' || success() }}
